---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  chef_omnibus_url: https://www.chef.io/chef/install.sh

platforms:
  - name: ubuntu-14.04
    driver:
      vm_hostname: moonlight.vps.com
      network:
        - ["forwarded_port", {guest: 80, host: 9999}]
        - ["private_network", {ip: "192.168.11.11"}]

suites:
  - name: moonlight
    run_list:
      - recipe[usersbags]
    attributes:
