name             'moonlight'
maintainer       'The Authors'
maintainer_email 'tungpt247@gmail.com'
license          'all_rights'
description      'Installs/Configures moon_light'
long_description 'Installs/Configures moon_light'
version          '0.1.0'

depends 'locale'
depends 'nodejs'
